version: "3"

services:
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--bind", "redis", "--port", "6379"]

  django:
    build: .
    container_name: django
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
    ports:
      - 8000:8000
